### ISSUE TITLE
Pooled connection

### ISSUE THREAD

**Issue by dokyungs** [bongcheon/go-blog#2]

**Comment by pawsong** [comment]
Socket connection pool seems to be managed by [mgo](https://github.com/go-mgo/mgo/blob/1407fa35a856bf446ccdaf9f618745114ba2f4e9/server.go#L105). How about just storing a mgo session instance?

**Comment by pawsong** [comment]
Feel free to check this pull request #3

**Comment by dokyungs** [comment]
Merged to develop.
